AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a Instance Profile, EC2 Instances, Security Groups and Load Balancer.

Parameters:
  pRoleName:
    Type: String
    Description: Name of IAM Role

Resources:
  # IAM Role 
  rEC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref pRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EC2ServicePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                Resource: arn:aws:s3:::*
              - Effect: Allow
                Action:
                  - rds:DescribeDBInstances
                  - rds:ListTagsForResource
                Resource: "*"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ssm:StartSession"
                  - "ssm:DescribeSessions"
                  - "ssm:TerminateSession"
                  - "ssmmessages:CreateControlChannel"
                  - "ssmmessages:OpenControlChannel"
                  - "ssmmessages:OpenDataChannel"
                  - "ec2messages:AcknowledgeMessage"
                  - "ec2messages:SendReply"
                Resource: !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
      Tags:
        - Key: Environment
          Value: dev

Outputs:
  oIAMRoleARN:
    Description: IAM Role ARN
    Value: !GetAtt rEC2InstanceRole.Arn
    Export:
      Name: oIAMRoleARN